version: 2.1

orbs:
  perl:
    jobs:
      # Build the distribution with dzil
      build:
        parameters:
          save-to-artifacts:
            description: Should the resulting build be saved to the artifacts for this pipeline?
            type: boolean
            default: false
          save-to-workspace:
            description: Should the resulting build be stored in the CircleCI workspace for this pipeline so that other jobs in the pipeline can test it?
            type: boolean
            default: false
        docker:
          - image: perldocker/perl-tester:5.30
        steps:
          - checkout
          - run:
              name: Build and Test Distribution
              command: /usr/local/bin/auto-build-and-test-dist
          - when:
              condition: << parameters.save-to-artifacts >>
              steps:
                - run:
                    name: Make tarball
                    command: tar -cvzf build.tar.gz build_dir
                - store_artifacts:
                    path: build.tar.gz
          - when:
              condition: << parameters.save-to-workspace >>
              steps:
                - persist_to_workspace:
                    root: .
                    paths: build_dir

      # Test the distribution with a single version of Perl on Linux
      test-linux:
        parameters:
          perl-version:
            description: The Perl version we want to test with
            type: string
            default: "5.30"
        docker:
          - image: perldocker/perl-tester:<< parameters.perl-version >>
        steps:
          - attach_workspace:
              at: /tmp/workspace
          - run:
              name: Install dependencies
              command: |
                cd /tmp/workspace/build_dir
                cpm install -g \
                --cpanfile cpanfile \
                --with-develop \
                --with-suggests \
                --show-build-log-on-failure
          - run:
              name: Run Tests
              command: |
                cd /tmp/workspace/build_dir
                prove -lr --jobs 2 t xt

workflows:
  main:
    jobs:
      - perl/build: { save-to-artifacts: true, save-to-workspace: true }
      - perl/test-linux:
          requires: [perl/build]
          matrix:
            parameters:
              perl-version:
                - "5.10"
                - "5.12"
                - "5.14"
                - "5.16"
                - "5.18"
                - "5.20"
                - "5.22"
                - "5.24"
                - "5.26"
                - "5.28"
                - "5.30"
